insert_policy:
  ckpt:
    left: outputs/learn/insert/left/v0/2024-05-14/10-46-01/ckpt/epoch_12_step_8000.ckpt
    right: outputs/learn/insert/right/v0/2024-05-14/10-46-06/ckpt/epoch_15_step_2000.ckpt
  interp_mask: False