policy:
  funnel:
    ckpt: outputs/learn/0826/fling.ckpt
    angle_degree_num: ${_load_:'./config/common.yaml', '.angle_degree_num'}
    distance_num: ${_load_:'./config/common.yaml', '.distance_num'}
  insert:
    type: act
    action_w: -0.3
    min_h: 0.01
    ckpt: outputs/learn/0910/act.ckpt
  keypoint:
    offset: 
      d: 0.03 # 0.03
      n: 0.02 # 0.02
    ckpt: outputs/learn/0826/kp.ckpt