policy:
  funnel:
    ckpt: outputs/learn/0826/fling.ckpt
    angle_degree_num: ${_load_:'./config/common.yaml', '.angle_degree_num'}
    distance_num: ${_load_:'./config/common.yaml', '.distance_num'}
  insert:
    type: qf
    ckpt:
      left: outputs/learn/0903/left.ckpt
      right: outputs/learn/0903/right.ckpt
    offset:
      press: [0., 0.]
      lift: [0.01, 0.01]
      drag: [0., 0.]
      rotate: [0., 0.]
  keypoint:
    offset: 
      d: 0.03 # 0.03
      n: 0.02 # 0.02
    ckpt: outputs/learn/0826/kp.ckpt