policy:
  funnel:
    ckpt: outputs/learn/0826/fling.ckpt
    angle_degree_num: ${_load_:'./config/common.yaml', '.angle_degree_num'}
    distance_num: ${_load_:'./config/common.yaml', '.distance_num'}
  insert:
    type: fix
    value:
      left:
        action_1: [-0.01, 0.49]
        action_2: [-0.11, 0.39]
      right:
        action_1: [+0.07, 0.45]
        action_2: [+0.16, 0.40]
    ckpt:
      left: outputs/learn/0903/leftimi.ckpt
      right: outputs/learn/0903/rightimi.ckpt
  keypoint:
    offset: 
      d: 0.03 # 0.03
      n: 0.02 # 0.02
    ckpt: outputs/learn/0826/kp.ckpt