sim_env:
  misc:
    tmp_path: ./.tmp
    use_tqdm: False
    enable_timer: False
    enable_debugger: False

  parameter:
    substeps:
      efficient_substeps: 10
      accurate_substeps: 20
      superreal_substeps: 40
    penetration:
      garment_robot_tolerance_sdf: -5e-3
      garment_hanger_tolerance_sdf: -5e-3
      hanger_gripper_tolerance_sdf: 2e-2
    dr:
      garment_E: [2e5, 4e5]
      garment_rho: [8e2, 12e2]
      garment_self_mu: [0.5, 0.8]
      garment_table_mu: [0.7, 1.0]
      garment_hanger_mu: [0.5, 0.8]

  sim:
    step_dt: 0.05
    substeps: ${..parameter.substeps.efficient_substeps}

    spatial_cfg:
      bounds: [[-1., -0.5, 0.2], [1., 1.5, 2.2]]
      xyz_size: [128, 128, 128]
      max_spatial_cell_size: 1024
      xyz_block_size: 8
      spatial_cell_chunk_size: 16
      max_bb_occupy_num: 128 # ~ 5 * 5 * 5, 8cm * 8cm * 8cm

    garment:
      skip: False
      CG:
        CG_max_iter: 64
        CG_relative_tol: 1e-3
        CG_dx_tol: 1e-6
      use_ccd: True
      ccd:
        num_max_step_iterations: 4
        num_cubic_solver_iterations: 16
        ccd_step_discount: 0.9
        min_step_length: 1e-3
      collision_mask_block_size: 16
      clamp_velocity:
        use: True
        threshold: 3. # v0
        strength: 1. # a, v-v0 -> log(a(v-v0) + 1) / a

    table:
      is_dynamic: False
    
    hanger:
      is_dynamic: False

    robot:
      is_dynamic: False
    
    gripper_left:
      is_dynamic: False
    
    gripper_right:
      is_dynamic: False

    garment_self_collision:
      name: self_collision
      max_vert_face_collision_pair: 12000
      max_edge_edge_collision_pair: 33000
      balance_distance: 4e-3
      barrier_width: 4e-3
      barrier_power: 3
      barrier_strength: 1e7
      dv_eps: 1e-7
      mu: 0.65
      friction_relative_velocity_scale: 0.1 # a: f=min(u*N, a*m*v/dt)

    garment_table:
      balance_distance: 5e-3
      mu: 0.85
      restitution: 0.0
      max_depenetration_velocity: 1.0
      response_time: 1e-1
      dv_eps: 1e-7

    garment_hanger:
      friction_type: Coulomb
      max_collision: 30000
      sample_dx: 4e-3
      balance_distance: 5e-3
      barrier_width: 5e-3
      barrier_strength: 2e7
      mu: 0.65
      friction_relative_velocity_scale: 0.5 # a: f=min(u*N, a*m*v/dt)
      dv_eps: 1e-7

    garment_robot:
      friction_type: Coulomb
      max_collision: 30000
      sample_dx: 3e-3
      balance_distance: 5e-3
      barrier_width: 5e-3
      barrier_strength: 1e7
      mu: 0.5
      friction_relative_velocity_scale: 0.5 # a: f=min(u*N, a*m*v/dt)
      dv_eps: 1e-7

  asset:
    garment:
      cfg:
        name: garment
        h: 2e-3
        rho: 1e3
        E: 3e5
        nu: 0.2
        alpha: 1e0
        stretch_relax_t: 2e-1
        bending_relax_t: 2e-1
      mesh_path: assets/clothes/old/0.obj
      translation: [0., 0.5, 1.5]

    table:
      cfg:
        name: table
        type: mesh
        sdf_cfg:
          calculate_sdf: True
          expand_distance: .032323
          size: [75, 50, 25]
      mesh_path: assets/misc/table.obj
      pos: [0., 0., 0.68, 1., 0., 0., 0.]

    robot:
      cfg:
        name: robot
        urdf_path: assets/robot/galbot_one_description_0521/galbot_one.urdf
        mesh_dir: assets/robot/galbot_one_description_0521/meshes
        sdf_cfg:
          calculate_sdf: True
          expand_distance: .012121 # > balance distance
          size: [30, 30, 30]
        activated_sdf_link:
        - left_gripper_base_link
        - right_gripper_base_link
      base_link: base_link
    
    hanger:
      cfg:
        name: hanger
        type: mesh
        surface_sample: 256
        sdf_cfg:
          calculate_sdf: True
          expand_distance: 0.0057975 # > balance distance
          size: [70, 70, 25]
      mesh_path: assets/hanger/hanger.obj
      mesh_vis_path: assets/hanger/hanger_vis.obj
      pos: [0., 1., 2., 1., 0., 0., 0.]

    grippers:
      left_cfg:
        name: gripper_left
        type: mesh
        surface_sample: 256
        sdf_cfg:
          calculate_sdf: True
          expand_distance: .012121
          size: [25, 25, 25]
      right_cfg:
        name: gripper_right
        type: ${..left_cfg.type}
        surface_sample: ${..left_cfg.surface_sample}
        sdf_cfg: ${..left_cfg.sdf_cfg}
      parameter:
        th_z: 0.035
        th_r: 0.02
        stiffness: 3e4
      prop:
        height: ${_eval_:'${..parameter.th_z} * 2.'}
        radius: ${..parameter.th_r}
    
  actor:
    robot:
      cfg:
        name: robot_actor