agent:
  cls: GalbotOneAgent
  init:
    base:
      name: base_link
      pos: [0.0, -0.35, 0.0, 0.70710678, 0., 0., 0.70710678]
    qpos:
      leg_joint1: 0.5
      leg_joint2: 1.2
      leg_joint3: 0.7
      leg_joint4: 0.

      left_arm_joint1: +0.50
      left_arm_joint2: -0.50
      left_arm_joint3: -2.50
      left_arm_joint4: -1.50
      left_arm_joint5: +1.00
      left_arm_joint6: +1.00
      left_arm_joint7: +1.50
      left_gripper_left_joint: 0.05
      left_gripper_right_joint: 0.05

      right_arm_joint1: -0.50
      right_arm_joint2: +0.50
      right_arm_joint3: +2.50
      right_arm_joint4: +1.50
      right_arm_joint5: -1.00
      right_arm_joint6: -1.00
      right_arm_joint7: -1.50
      right_gripper_left_joint: 0.05
      right_gripper_right_joint: 0.05

      head_joint1: 0.0
      head_joint2: 0.0

  grasp:
    left:
      link: left_gripper_tcp_link
      joints:
      - left_arm_joint1
      - left_arm_joint2
      - left_arm_joint3
      - left_arm_joint4
      - left_arm_joint5
      - left_arm_joint6
      - left_arm_joint7
    right:
      link: right_gripper_tcp_link
      joints:
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6
      - right_arm_joint7

  action_rpy:
    fling:
      pick_points:
        leg_joint_coeff:
          leg_joint3: 1.5
    lift:
      pick_points:
        leg_joint_val:
          leg_joint3: ${_eval_:'0.4 + ${agent.init.qpos.leg_joint3}'}
          leg_joint4: 0.2
    press:
      press: 
        leg_joint_val: ${...lift.pick_points.leg_joint_val}
        right: [0.7853981633974483, 0.0, +0.7853981633974483] # hanger
    drag:
      regrasp:
        leg_joint_val:
          leg_joint3: ${_eval_:'0.4 + ${agent.init.qpos.leg_joint3}'}
          leg_joint4: 0.0
        left:  [0., 0., -2.356194490192345] # hanger
      pick_points:
        leg_joint_val: ${..regrasp.leg_joint_val}
      drag: ${.pick_points}
    rotate:
      rotate:
        leg_joint_val: ${...drag.regrasp.leg_joint_val}
        left:  [0., 0., -3.141592653589793] # hanger
      liftup1:
        left:  [-0.7853981633974483, 0., -3.141592653589793] # hanger
      liftup2:
        left:  [-1.5707963267948966, 0., -3.141592653589793] # hanger

  inverse_kinematics:
    solver:
      max_iter: 64
      fix_joint:
      - leg_joint1
      - leg_joint2
      - leg_joint3
      - leg_joint4
    init:
      default:
        left:
          left_arm_joint1: +0.50
          left_arm_joint2: +0.50
          left_arm_joint3: -2.00
          left_arm_joint4: -1.50
          left_arm_joint5: +1.00
          left_arm_joint6: +1.00
          left_arm_joint7: +1.50
        right:
          right_arm_joint1: -0.50
          right_arm_joint2: -0.50
          right_arm_joint3: +2.00
          right_arm_joint4: +1.50
          right_arm_joint5: -1.00
          right_arm_joint6: -1.00
          right_arm_joint7: -1.50

  camera:
    prop:
      # small: # d415 p[317.029 239.639] f[606.946 606.588] @ 640x480
      #   height: 128
      #   width: 192
      #   fx: 159.2
      #   fy: 159.2
      #   cx: 95.1
      #   cy: 61.2
      #   skew: 0.
      small:
        height: 512
        width: 512
        fx: 192.
        fy: 192.
        cx: 256.
        cy: 256.
        skew: 0.
      medium: # side view
        height: 360
        width: 540
        fx: 600.0
        fy: 600.0
        cx: 270.0
        cy: 180.0
        skew: 0.
      large: # side view
        height: 720
        width: 1080
        fx: 1200.0
        fy: 1200.0
        cx: 540.0
        cy: 360.0
        skew: 0.
    top:
      link: head_link2
      origin: 
        xyz: [0., 0., 0.]
        rpy: [0., 0., 0.]
    left:
      link: left_gripper_tcp_link
      origin: 
        xyz: [0., 0., 0.]
        rpy: [0., 0., 0.]
    right:
      link: right_gripper_tcp_link
      origin: 
        xyz: [0., 0., 0.]
        rpy: [0., 0., 0.]
    side:
      pos: [-1.5, +2.0, +3.0, 0.85355339, 0.14644661, 0.35355339, -0.35355339]
    direct: 
      pos: [0., -0.05, 1.3, 0.65327975, -0.27059975, 0.27059635, 0.65328321] # rpy=(0., pi/4, pi/2)
      # pos: [0.0, 0.03, 1.50, 0.61237244, -0.35355339, 0.35355339, 0.61237244] # rpy=(0., pi/3, pi/2)
    rand:
      prop:
        fx: 8.
        fy: 8.
        cx: 16.
        cy: 16.
      pose:
        xyz: 0.02
        rot: 0.03
  
  policy_obs:
    reproject:
      camera_prop:
        height: 128
        width: 128
        fx: 256.
        fy: 256.
        cx: 64.
        cy: 64.
        skew: 0.
      camera_pose: [0., 0.5, 2.5, 0.5, -0.5, 0.5, 0.5]
      x1x2y1y2:
        double_side: [-1e6, +1e6, -1e6, +1e6]
        hanger: [-1e6, +1e6, -1e6, +1e6]
        inverse_side: [-0.15, +0.15, 0.35, 0.65]