funnel_policy:
  fling:
    query:
      per_batch: 64
      num_iter: 16
    prob:
      fail: 0.2
      normal: 0.8
    heuristic:
    - [+0.03, +0.03, "eq", 0]
    - [-0.03, +0.03, "eq", 0]
    - [-0.03, -0.03, "eq", 0]
    - [+0.03, -0.03, "eq", 0]
    - [+0.042, 0.00, "eq", 0]
    - [-0.042, 0.00, "eq", 0]
    - [0.00, +0.042, "eq", 0]
    - [0.00, -0.042, "eq", 0]
  pick_place:
    query: ${..fling.query}
    prob:
      fail: 0.1
      success: 0.9