funnel_gym:
  parameter:
    damp_per_substep: 1e-2
    # pick_points_offset_0_layer: 2e-2
    # pick_points_offset_max_value: 3e-2

  primitive:
    init_garment:
      x: [-0.05, +0.05]
      y: [+0.45, +0.55]
      z: [1.4, 1.5]

      up_x: 0.0
      up_y: 0.5

      steps: [10, 20, 10, 20, 20]
    fling:
      normal:
        action_space:
          center: [0.0, 0.5]
          radius: 0.25
          distance: [0.20, 0.40]
          angle_degree: [-90., +90.]
      key_points:
        pick_points:
          h_upper: 0.20
          h_inter: 0.08
          h_delta: 0.015
          h_later: 0.08
          steps: [9, 6, 6, 4]
        lift_up:
          x: 
            scale: 1.2
          y: 0.35 # 0.65
          h: 0.70
          steps: [20]
        fling_forwards:
        - y: 0.70 # 0.30
          h: 0.70
          steps: 8
          wait: 3
        - y: 0.60 # 0.30
          h: 0.30
          steps: 6
        - y: 0.30 # 0.70
          h: 0.10
          steps: 8
          wait: 5
        reset:
          h_upper: 0.20
          steps: [10, 5]
    pick_place:
      action_space:
        min: [-0.10, 0.40]
        max: [+0.10, 0.60]
      pick_points: ${..fling.key_points.pick_points}
      drag_step: [20, 10]
      reset: ${..fling.key_points.reset}
    keypoints:
      action_space:
        dist_range: [0.14, 0.22]
        xyc: [0.0, 0.5]
        radius_max: 0.30
      key_points:
        pick_points: ${...fling.key_points.pick_points}
        lift_up:
          x: 
            scale: 1.2
          y: 0.65
          h: 0.75
          steps: [20]
        fling_forwards:
        - y: 0.05 # insert gym: 0.15
          h: 0.75
          steps: 10
        - y: 0.30 # insert gym: 0.35
          h: 0.40
          steps: 10
        - y: 0.48
          h: 0.05
          steps: 10
        reset:
          h_upper: 0.20
          steps: [10, 10]
  
  reward:
    coverage:
      dx: 0.005
      dy: 0.005
      nx: 200
      ny: 200
      xmin: -0.5
      ymin: +0.0
    orientation:
      keypoints_name: 
      - upper_left
      - upper_right
      - armpit_left
      - armpit_right
      target:
        xyz: [0., 0.50, 0.70]
        rpy: [0., 0., 0.]
    keypoints:
      gripper_radius: 0.015
      dist_threshold: 0.030

      