hydra:
  run:
    dir: outputs/learn/${train.path.exp_name}/${train.path.version_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  job:
    chdir: True

run: 
  mode: train

data:
  common:
    valid_size: 0.2
    batch_size: 256
    num_workers: 32
    drop_last: True
  dataset:
    dtype: ${misc.hardware.dtype}
    aug:
      depth_scale: [0.5, 1.5]
      tilt: 3e-2
      noise_std: 5e-3
      use_conv_on_noise: True
      random_flip_mask: False
      flip_mask_prob: 0.05

pl:
  model:
    d_unit: 0.1
    qf_dist_smooth: 0.02
    step_encode_bias: -1.5
    critic:
      channels_list: [6, 8, 12, 16, 24, 32]
      output_mlp_hidden: [16, 16]
    policy:
      channels_list: [16, 32, 64, 128, 256, 512]
      output_mlp_hidden: [256, 256]
  learn:
    gamma: 0.5 # 0.9
    tau: 0.005
    alpha: 0.001
    target_update_interval: 10
    lr: 1e-4
    weight_decay: 1e-2
    valid:
      plot_batch_idx: [0]
      plot_dense_predict_num: 16

train:
  path:
    exp_name: insertsac
    version_name: v0
    data_paths: ["outputs/data"]
    ckpt:
  cfg:
    max_steps: 5000
    limit_train_batches: 1. # use how much data to train
    limit_val_batches: 1. # use how much data to validate
    log_every_n_steps: 10
    val_check_interval: 100 # How often to evaluate on the validation set
    ckpt_every_n_steps: 200

misc:
  seed: 0 # ${_eval_:'int(__import__("numpy").random.randint(0, 2 ** 31))'}
  step_offset: 0
  hardware:
    precision: high # [highest, high, medium]
    cuda: True
    gpuids: [0]
    dtype: float32
  debug:
    profiler: Simple
    model_summary_max_depth: 5