hydra:
  job:
    chdir: True
  job_logging:
    root:
      level: INFO
      handlers:
      - file

output:
  collect_mode: False
  total_traj: 2
  export:
    base_dir: "."
    side_view_export_mesh: True
    obs_export_mesh: ${_eval_:'not ${output.collect_mode}'}
  e2e_export_obs: True

control:
  skip_init_garment: False
  state_path:

glb_cfg:
  seed: ${_eval_:'int(__import__("numpy").random.randint(0, 2 ** 31))'}
  batch_size: 2
  default_float: float32
  default_int: int32
  torch_device: cuda
  default_mass: 1.
  default_inertia: 1.
  log_verbose: 1

setup:
  cuda: 0
  taichi:
    arch: cuda
    device_memory_GB: 2

    debug: False
    advanced_optimization: True
    fast_math: False
    offline_cache: True

sim_env: ${_load_:'./config/env/sim_env.yaml', '.sim_env'}

insert_gym: ${_load_:'./config/policy/insert/insert_gym_e2e.yaml', '.insert_gym'}

insert_policy:
  name: debug # [debug, act, dfp]
  debug:
    steps_in_sim: 2
    max_step: 150
    debug_action_dir: xxx # xxx/batch_idx/action/action_idx.npy
  act:
    steps_in_sim: 2
    max_step: 150
    action_w: -0.3
    ckpt: xxx
  dfp:
    steps_in_sim: 2
    max_step: 150
    ddpm_inference_timestep: 100
    use_time_ensemble: True
    act_exe_len: 8 # used if use_time_ensemble==False
    action_w: -0.3 # used if use_time_ensemble==True
    ckpt: xxx

agent: ${_load_:'./config/agent/galbot_one_agent.yaml', '.agent'}

overwrite:
  sim_env:
    misc:
      enable_timer: ${_eval_:'${output.collect_mode} == False'}
  insert_gym:
    parameter:
      min_h: 0.02